### ISSUE TITLE
非常好用，目前还没有上传公共仓库吗

### ISSUE THREAD

**Issue by eric7166** [flyhero/easy-log#1]
看文档，非常好用，大力支持👍🏻
目前还没有上传公共仓库吗，目前阿里云仓库搜索不到
<dependency>
            <groupId>com.github.flyhero</groupId>
            <artifactId>easylog-spring-boot-starter</artifactId>
            <version>1.0.0</version>
        </dependency>

**Comment by flyhero** [comment]
> 看文档，非常好用，大力支持👍🏻 目前还没有上传公共仓库吗，目前阿里云仓库搜索不到 com.github.flyhero easylog-spring-boot-starter 1.0.0

已上传到中央仓库：https://search.maven.org/search?q=g:io.github.flyhero
```
<dependency>
  <groupId>io.github.flyhero</groupId>
  <artifactId>easylog-spring-boot-starter</artifactId>
  <version>1.0.1</version>
</dependency>
````
