### ISSUE TITLE
支持不同模块 写入到不同的文件么? 只能默认到公共日志么?

### ISSUE THREAD

**Issue by lumanyy** [flyhero/easy-log#6]
支持不同模块 写入到不同的文件么? 只能默认到公共日志么?

**Comment by lumanyy** [comment]
没找到怎么配置自定义的log appender

**Comment by flyhero** [comment]
> 支持不同模块 写入到不同的文件么? 只能默认到公共日志么?

一般都是把操作日志存储的数据库的，以便查询。

**Comment by lumanyy** [comment]
那如果是监控日志呢?比如缓存监控 三方调用监控 类似这种 非操作日志呢?

**Comment by lumanyy** [comment]
应该也是类似 系统日志吧? 比如调用了某个三方系统 是否成功 出入参 耗时 等 可能涉及脱密

**Comment by flyhero** [comment]
- 这是给开发人员看的： 
监控日志、系统日志，这些应该是你们项目中使用AOP、log日志框架自己记录到日志文件中的。
- 这是给客户或管理人员看的：
 easylog中的所说的日志为人为操作产生的方便可视化的操作记录。

如果你要使用easylog，只需要实现 ILogRecordService 接口，信息都在 EasyLogInfo 类中，然后按照自己的方式想存储在哪里就存储在哪里，想用什么方式处理 都可以。

@yeyinghao
